### ISSUE TITLE
Sechelt does not exit VR properly with Chromium

### ISSUE THREAD

**Issue by caseyyee** [MozVR/mozvr-site#42]
![image](https://cloud.githubusercontent.com/assets/1560884/12592823/fad389c0-c422-11e5-994b-d9344e9cc3e8.png)

**Comment by cvan** [comment]
This seems like an issue with `<iframe>`ing in the Chromium builds. Also reproducible here:

http://threejs.org/examples/#webvr_cubes

It's probably not worth filing since the new WebVR API doesn't use the Fullscreen API and Brandon has deprecated these pre-v1.0 Chromium builds. If it's actually a WebGL/VR-specific issue though, we should file it here: https://github.com/toji/chrome-webvr-issues/issues

**Comment by caseyyee** [comment]
It should be fixable.   Even with the new API we will need to properly handle the exit so that we return back to mono rendering anyways.

**Comment by cvan** [comment]
These Chromium builds are deprecated.
